spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration #현재 DB를 사용하지 않아 임시 조치

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
jwt:
  secret: "test1234test1234test1234test1234test1234test1234"  # 32바이트 이상 임의 문자열
  expiration: 3600000 # 1시간 (1000 * 60 * 60)

