spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/apa_user?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

logging:
  level:
    root: INFO
    com.apa.user: DEBUG
    org.hibernate.SQL: DEBUG
